export const curriculum = {
  "total_units": 50,
  "units": [
    { "id": "01_temel_islemler", "order": 1, "module": "Modül 1: Temel Matematik & Sayılar", "title": "Temel İşlemler, Parantez Açma ve İşlem Önceliği", "page": 1 },
    { "id": "02_temel_kavramlar", "order": 2, "module": "Modül 1: Temel Matematik & Sayılar", "title": "Temel Kavramlar & Sayı Kümeleri", "page": 8 },
    { "id": "03_tek_cift_sayilar", "order": 3, "module": "Modül 1: Temel Matematik & Sayılar", "title": "Tek ve Çift Sayılar", "page": 13 },
    { "id": "04_asal_sayilar", "order": 4, "module": "Modül 1: Temel Matematik & Sayılar", "title": "Asal Sayılar & Aralarında Asal Sayılar", "page": 17 },
    { "id": "05_ardisik_sayilar", "order": 5, "module": "Modül 1: Temel Matematik & Sayılar", "title": "Ardışık Sayılar ve Terim Sayısı Formülleri", "page": 20 },
    { "id": "06_faktoriyel", "order": 6, "module": "Modül 1: Temel Matematik & Sayılar", "title": "Faktöriyel Kavramı ve Sadeleştirmeler", "page": 25 },
    { "id": "07_sayi_basamaklari", "order": 7, "module": "Modül 1: Temel Matematik & Sayılar", "title": "Sayı Basamakları & Basamak Çözümleme", "page": 29 },
    { "id": "08_taban_aritmetigi", "order": 8, "module": "Modül 1: Temel Matematik & Sayılar", "title": "Taban Aritmetiği ve Dört İşlem", "page": 35 },
    { "id": "09_bolme", "order": 9, "module": "Modül 1: Temel Matematik & Sayılar", "title": "Bölme İşlemi ve Kalan Bağıntıları", "page": 38 },
    { "id": "10_bolunebilme", "order": 10, "module": "Modül 1: Temel Matematik & Sayılar", "title": "Bölünebilme Kuralları (2,3,4,5,8,9,11)", "page": 41 },
    { "id": "11_asal_carpanlar", "order": 11, "module": "Modül 1: Temel Matematik & Sayılar", "title": "Asal Çarpanlara Ayırma & Pozitif Bölen Sayısı", "page": 46 },
    { "id": "12_ebob_ekok", "order": 12, "module": "Modül 1: Temel Matematik & Sayılar", "title": "EBOB - EKOK & Periyodik Problemler", "page": 49 },
    { "id": "13_rasyonel_sayilar", "order": 13, "module": "Modül 2: Cebirsel İfadeler ve Denklemler", "title": "Rasyonel Sayılar ve Merdivenli Kesirler", "page": 56 },
    { "id": "14_ondalikli_sayilar", "order": 14, "module": "Modül 2: Cebirsel İfadeler ve Denklemler", "title": "Ondalıklı Sayılar & Devirli Ondalık Açılımlar", "page": 62 },
    { "id": "15_basit_esitsizlikler", "order": 15, "module": "Modül 2: Cebirsel İfadeler ve Denklemler", "title": "Basit Eşitsizlikler ve Sayı Aralıkları", "page": 66 },
    { "id": "16_mutlak_deger", "order": 16, "module": "Modül 2: Cebirsel İfadeler ve Denklemler", "title": "Mutlak Değer Özellikleri ve Eşitsizlikleri", "page": 73 },
    { "id": "17_uslu_sayilar", "order": 17, "module": "Modül 2: Cebirsel İfadeler ve Denklemler", "title": "Üslü Sayılar ve Üslü Denklemler", "page": 81 },
    { "id": "18_koklu_sayilar", "order": 18, "module": "Modül 2: Cebirsel İfadeler ve Denklemler", "title": "Köklü Sayılar ve Eşlenik Çarpımları", "page": 89 },
    { "id": "19_carpanlara_ayirma", "order": 19, "module": "Modül 2: Cebirsel İfadeler ve Denklemler", "title": "Çarpanlara Ayırma ve Özdeşlikler", "page": 99 },
    { "id": "20_birinci_dereceden_denklemler", "order": 20, "module": "Modül 2: Cebirsel İfadeler ve Denklemler", "title": "I. Dereceden Bir ve İki Bilinmeyenli Denklemler", "page": 108 },
    { "id": "21_oran_oranti", "order": 21, "module": "Modül 2: Cebirsel İfadeler ve Denklemler", "title": "Oran - Orantı ve Orantı Çeşitleri", "page": 113 },
    { "id": "22_sayi_kesir_problemleri", "order": 22, "module": "Modül 3: Problemler Dünyası", "title": "Sayı ve Kesir Problemleri", "page": 121 },
    { "id": "23_yas_problemleri", "order": 23, "module": "Modül 3: Problemler Dünyası", "title": "Yaş Problemleri", "page": 131 },
    { "id": "24_karisim_problemleri", "order": 24, "module": "Modül 3: Problemler Dünyası", "title": "Karışım Problemleri", "page": 135 },
    { "id": "25_isci_havuz_problemleri", "order": 25, "module": "Modül 3: Problemler Dünyası", "title": "İşçi ve Havuz Problemleri", "page": 138 },
    { "id": "26_yuzde_kar_zarar_problemleri", "order": 26, "module": "Modül 3: Problemler Dünyası", "title": "Yüzde, Kâr, Zarar ve İskonto Problemleri", "page": 141 },
    { "id": "27_hiz_problemleri", "order": 27, "module": "Modül 3: Problemler Dünyası", "title": "Hız ve Hareket Problemleri", "page": 149 },
    { "id": "28_grafik_problemleri", "order": 28, "module": "Modül 3: Problemler Dünyası", "title": "Grafik ve Tablo Okuma Problemleri", "page": 156 },
    { "id": "29_kumeler", "order": 29, "module": "Modül 4: İleri Konular & Sayısal Mantık", "title": "Kümeler ve Küme İşlemleri", "page": 166 },
    { "id": "30_kume_problemleri", "order": 30, "module": "Modül 4: İleri Konular & Sayısal Mantık", "title": "Küme Problemleri", "page": 171 },
    { "id": "31_islem", "order": 31, "module": "Modül 4: İleri Konular & Sayısal Mantık", "title": "Özel Tanımlı İşlem", "page": 175 },
    { "id": "32_moduler_aritmetik", "order": 32, "module": "Modül 4: İleri Konular & Sayısal Mantık", "title": "Modüler Aritmetik & Kalan Sınıfları", "page": 179 },
    { "id": "33_permutasyon", "order": 33, "module": "Modül 4: İleri Konular & Sayısal Mantık", "title": "Permütasyon (Sıralama) & Tekrarlı Permütasyon", "page": 183 },
    { "id": "34_kombinasyon", "order": 34, "module": "Modül 4: İleri Konular & Sayısal Mantık", "title": "Kombinasyon (Seçme ve Gruplama)", "page": 188 },
    { "id": "35_olasilik", "order": 35, "module": "Modül 4: İleri Konular & Sayısal Mantık", "title": "Olasılık Hesabı", "page": 192 },
    { "id": "36_fonksiyonlar", "order": 36, "module": "Modül 4: İleri Konular & Sayısal Mantık", "title": "Fonksiyonlar (Tanım, Değer, Ters, Bileşke)", "page": 198 },
    { "id": "37_sayisal_mantik", "order": 37, "module": "Modül 4: İleri Konular & Sayısal Mantık", "title": "Sayısal Mantık, Şekil Yeteneği & Akıl Yürütme", "page": 206 },
    { "id": "38_dogruda_acilar", "order": 38, "module": "Modül 5: Geometri", "title": "Geometri: Doğruda Açılar", "page": 213 },
    { "id": "39_ucgende_acilar", "order": 39, "module": "Modül 5: Geometri", "title": "Geometri: Üçgende Açılar", "page": 217 },
    { "id": "40_dik_ucgen", "order": 40, "module": "Modül 5: Geometri", "title": "Geometri: Dik Üçgen & Pisagor / Öklid", "page": 223 },
    { "id": "41_ikizkenar_eskenar_ucgen", "order": 41, "module": "Modül 5: Geometri", "title": "Geometri: İkizkenar ve Eşkenar Üçgen", "page": 227 },
    { "id": "42_aciortay", "order": 42, "module": "Modül 5: Geometri", "title": "Geometri: Üçgende Açıortay Bağıntıları", "page": 230 },
    { "id": "43_kenarortay", "order": 43, "module": "Modül 5: Geometri", "title": "Geometri: Kenarortay ve Ağırlık Merkezi", "page": 234 },
    { "id": "44_ucgende_alan", "order": 44, "module": "Modül 5: Geometri", "title": "Geometri: Üçgende Alan Hesabı", "page": 239 },
    { "id": "45_ucgende_benzerlik", "order": 45, "module": "Modül 5: Geometri", "title": "Geometri: Üçgende Benzerlik ve Eşlik", "page": 244 },
    { "id": "46_cokgenler", "order": 46, "module": "Modül 5: Geometri", "title": "Geometri: Çokgenler ve Düzgün Çokgenler", "page": 257 },
    { "id": "47_dortgenler", "order": 47, "module": "Modül 5: Geometri", "title": "Geometri: Dörtgenler, Paralelkenar, Dikdörtgen, Kare, Yamuk", "page": 263 },
    { "id": "48_cember_daire", "order": 48, "module": "Modül 5: Geometri", "title": "Geometri: Çemberde Açılar, Uzunluk ve Dairede Alan", "page": 283 },
    { "id": "49_kati_cisimler", "order": 49, "module": "Modül 5: Geometri", "title": "Geometri: Katı Cisimler (Prizma, Silindir, Koni, Küre)", "page": 293 },
    { "id": "50_analitik_geometri", "order": 50, "module": "Modül 5: Geometri", "title": "Geometri: Noktanın ve Doğrunun Analitik İncelenmesi", "page": 301 }
  ]
};
